image: debian/sid
packages:
  - golang
sources:
  - https://git.sr.ht/~retzkek/pfeil
tasks:
  - build: |
      cd pfeil
      make
  - test: |
      cd pfeil
      ./example.sh
  - package: |
      cd pfeil
      make tarball
artifacts:
  - pfeil/pfeil.tar.gz
